# Generated by Django 4.1.7 on 2023-06-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0002_username_vote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='username',
            table=None,
        ),
    ]
