# Generated by Django 4.1.7 on 2023-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0003_alter_username_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('pid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pnumber', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('paddress', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=200)),
                ('discription', models.TextField(max_length=200)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
