# Generated by Django 4.1.7 on 2023-06-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0004_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='pid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='username',
            name='aadharNumber',
            field=models.TextField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
